fail_fast: false
exclude: |
    (?x)^(
        tests/data/.*
    )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
#  - repo: https://github.com/astral-sh/ruff-pre-commit
#    # Ruff version.
#    rev: v0.0.275
#    hooks:
#      - id: ruff
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: poetry run isort .
        language: system
        pass_filenames: false
  - repo: local
    hooks:
    -   id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade --py37-plus
        language: python
        types: [python]
        pass_filenames: true
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: poetry run black .
        language: system
        pass_filenames: false